name: Frontend CI

on:
  push:
    branches: [ develop, feature/* ]
    paths: [ 'frontend/**' ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      
      - run: cd frontend && yarn install
      - run: cd frontend && yarn build
      - run: cd frontend && yarn test